SELECT 
	F.FLIGHT_ID,
	A.NO_AIRCRAFT,
	A.NAME,
	F.DEPARTURE_DT,
	COUNT(F.FLIGHT_ID) AS Count_Of_Passengers 
FROM FLIGHTS AS F
JOIN AIRCRAFTS AS A ON A.AIRCRAFT_ID=F.AIRCRAFT_ID
JOIN RESERVATIONS AS R ON F.FLIGHT_ID=R.FLIGHT_ID
WHERE F.DEPARTURE_DT BETWEEN'2018-01-01' AND '2018-12-29'
GROUP BY 
	F.FLIGHT_ID,
	A.NO_AIRCRAFT,
	A.NAME,
	F.DEPARTURE_DT
ORDER BY F.DEPARTURE_DT --DESC

