SELECT TOP 10
	F.FLIGHT_ID,
	A.NO_AIRCRAFT,
	A.NAME,
	SUM(R.BILLED_AMT) AS MONEY_CASHED 
FROM FLIGHTS AS F
JOIN AIRCRAFTS AS A ON A.AIRCRAFT_ID=F.AIRCRAFT_ID
JOIN RESERVATIONS AS R ON F.FLIGHT_ID=R.FLIGHT_ID
WHERE A.OUT_SERVICE_DT>= GETDATE()
GROUP BY 
	F.FLIGHT_ID,
	A.NO_AIRCRAFT,
	A.NAME
ORDER BY MONEY_CASHED DESC
