WITH SUB_QUERY AS 
(
SELECT 
	F.FLIGHT_ID,
	F.DEPARTURE_AIRPORT_NO,
	F.DESTINATION_AIRPORT_NO,
	A.PASSENGER_SEATS_TOT- COUNT(F.FLIGHT_ID) AS EMPTY_SEATS
FROM FLIGHTS AS F
JOIN AIRCRAFTS AS A ON A.AIRCRAFT_ID=F.AIRCRAFT_ID
JOIN RESERVATIONS AS R ON F.FLIGHT_ID=R.FLIGHT_ID
WHERE F.DEPARTURE_DT BETWEEN'2018-01-01' AND '2018-12-29'
GROUP BY 
	F.FLIGHT_ID,
	F.DEPARTURE_AIRPORT_NO,
	F.DESTINATION_AIRPORT_NO,
	A.PASSENGER_SEATS_TOT
)
SELECT 
	SUB_QUERY.DEPARTURE_AIRPORT_NO AS DEPARTURE_AIRPORT_NO,
	SUB_QUERY.DESTINATION_AIRPORT_NO AS DESTINATION_AIRPORT_NO,
	AVG(SUB_QUERY.EMPTY_SEATS) AS AVERAGE_OF_EMPTY_SEATS
FROM SUB_QUERY 
GROUP BY 
	SUB_QUERY.DEPARTURE_AIRPORT_NO,
	SUB_QUERY.DESTINATION_AIRPORT_NO
ORDER BY AVERAGE_OF_EMPTY_SEATS DESC




